### ISSUE TITLE
GameStory

### ISSUE THREAD

**Issue by dantcho** [hristo2612/LogX#1]
Съчинявам си история, по това което виждам написано като код и слагам нещо от мен. Ако нещо не съм уцелил можете да редактирате това issue. 

Героят ни е кораб който се опитва да унищожи вражеските кораби и да оцелее. Започва играта с 5 живота и обикновен кораб(Level0). Освен вражески кораби от горе се изсипват и бонуси (точки, животи , ъпгрейд на кораба, ..). Когато кораба ни е уцелен той се връща към кораба преди ъпгрейда или избухва ако е обикновен кораб(Level0).
Ъпгрейдите на кораба да не са повече от 4.
Level 0 - малкото синьо корабче с единична стрелба.   |
Level 1 - кораб с двойна стрелба. ||
Level 2 -  ||/
Level 3 - |||/
Кораба да става все по голям с нарастване на ъпгрейда. за да може да бъде улучван по лесно.
"Лошите" кораби също да имат нива на ъпгрейд.
На всеки 100 точки да се увеличава нивото на играта, а от там - скоростта , честота за появяване на "лошите" кораби и нивото им на ъпгрейд,  
Бонусите може да са в формата на метеори, които първо трябва да гръмнеш, а после да прибереш или пък да изпадат от "лошите", които имат по високо ниво на ъпгрейд и така да им го крадеш. 

Какво ще кажете?

**Comment by pstdevbg** [comment]
Идеите са добри и ние сме обмисляли подобни неща, но проблемът е, че не остава много време за работа по проекта, а и нямаме много опит с разработката на игри, особено под JS и HTML.

За сега предлагам да направим по-простите и по-лесните от неща като:
-Shooting enemies (вражеските кораби също да стрелят)
-Player lives (играча да има определен брой животи)
-Player death (играча да може да умре и да се изписва някакво съобщение и опция за рестартиране на играта)
-Score system (система за точки, примерно всеки убит вражески кораб да дава по 100)
-Level Boss (при събиране на определен брой точки или след определено време да се появява голям вражески кораб, който има определен живот, както и по-силни атаки от другите)
